export const images = {
  appleLogo: require('../../../assets/img/appleLogo.png'),
  facebookLogo: require('../../../assets/img/fbLogo.png'),
  googleLogo: require('../../../assets/img/googleLogo.png'),
  foodieLogo: require('../../../assets/img/foodie.png'),
  background: require('../../../assets/img/background.png'),
  searchIcon: require('../../../assets/img/searchIcon.png'),
  filter: require('../../../assets/img/filter.png'),
  restaurantImage: require('../../../assets/img/restaurant1.png'),
  restaurantRating: require('../../../assets/img/ratings.png'),
  restaurantFavorite: require('../../../assets/img/heart.png'),
  rdFavorite: require('../../../assets/img/heart-small.png'),
  locationIcon: require('../../../assets/img/location.png'),
  backButton:require('../../../assets/img/back.png'),
};
